//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; implements IView, but is not a class. Try making it a class and inherit MonoBehaviour..
        /// </summary>
        internal static string AnalyzeDesc_MV001 {
            get {
                return ResourceManager.GetString("AnalyzeDesc_MV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; implements IView, but does not inherit MonoBehaviour..
        /// </summary>
        internal static string AnalyzeDesc_MV002 {
            get {
                return ResourceManager.GetString("AnalyzeDesc_MV002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; implements base IView. Use IView&lt;T&gt; instead..
        /// </summary>
        internal static string AnalyzeDesc_MV003 {
            get {
                return ResourceManager.GetString("AnalyzeDesc_MV003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; implements IView, but does not use [RequireComponent(typeof(ViewGameObject))] attribute..
        /// </summary>
        internal static string AnalyzeDesc_MV004 {
            get {
                return ResourceManager.GetString("AnalyzeDesc_MV004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to class..
        /// </summary>
        internal static string AnalyzeFix_MV001 {
            get {
                return ResourceManager.GetString("AnalyzeFix_MV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit MonoBehaviour..
        /// </summary>
        internal static string AnalyzeFix_MV002 {
            get {
                return ResourceManager.GetString("AnalyzeFix_MV002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add [RequireComponent(typeof(ViewGameObject))] attribute..
        /// </summary>
        internal static string AnalyzeFix_MV004 {
            get {
                return ResourceManager.GetString("AnalyzeFix_MV004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove IView interface..
        /// </summary>
        internal static string AnalyzeTitle_MV001 {
            get {
                return ResourceManager.GetString("AnalyzeTitle_MV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit MonoBehaviour..
        /// </summary>
        internal static string AnalyzeTitle_MV002 {
            get {
                return ResourceManager.GetString("AnalyzeTitle_MV002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use generic version of IView..
        /// </summary>
        internal static string AnalyzeTitle_MV003 {
            get {
                return ResourceManager.GetString("AnalyzeTitle_MV003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RequireComponent for ViewGameObject..
        /// </summary>
        internal static string AnalyzeTitle_MV004 {
            get {
                return ResourceManager.GetString("AnalyzeTitle_MV004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IView.
        /// </summary>
        internal static string IVew {
            get {
                return ResourceManager.GetString("IVew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelView.
        /// </summary>
        internal static string IView_Namespace {
            get {
                return ResourceManager.GetString("IView Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonoBehaviour.
        /// </summary>
        internal static string MonoBehaviour {
            get {
                return ResourceManager.GetString("MonoBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireComponent.
        /// </summary>
        internal static string RequireComponent {
            get {
                return ResourceManager.GetString("RequireComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnityEngine.
        /// </summary>
        internal static string UnityEngine_Namespace {
            get {
                return ResourceManager.GetString("UnityEngine Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewGameObject.
        /// </summary>
        internal static string ViewGameObject {
            get {
                return ResourceManager.GetString("ViewGameObject", resourceCulture);
            }
        }
    }
}
